"""add sensor_reading_monthly_aggregates table

Revision ID: 4d1a1503f306
Revises: 9021458f6b9f
Create Date: 2026-05-10 14:13:01.018096

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4d1a1503f306"
down_revision: str | Sequence[str] | None = "9021458f6b9f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sensor_reading_monthly_aggregates",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("sensor_id", sa.Integer(), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("month", sa.Integer(), nullable=False),
        sa.Column("reading_count", sa.Integer(), nullable=False),
        sa.Column("moisture_avg", sa.Float(), nullable=False),
        sa.Column("moisture_min", sa.Float(), nullable=False),
        sa.Column("moisture_max", sa.Float(), nullable=False),
        sa.Column("soil_temperature_avg", sa.Float(), nullable=True),
        sa.Column("soil_temperature_min", sa.Float(), nullable=True),
        sa.Column("soil_temperature_max", sa.Float(), nullable=True),
        sa.Column("electrical_conductivity_avg", sa.Float(), nullable=True),
        sa.Column("archived_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["sensor_id"], ["sensors.id"], name=op.f("fk_sensor_reading_monthly_aggregates_sensor_id_sensors")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sensor_reading_monthly_aggregates")),
        sa.UniqueConstraint("sensor_id", "year", "month", name="uq_sensor_reading_aggregate_month"),
    )
    with op.batch_alter_table("sensor_reading_monthly_aggregates", schema=None) as batch_op:
        batch_op.create_index("ix_sensor_reading_aggregate_year_month", ["year", "month"], unique=False)
        batch_op.create_index(batch_op.f("ix_sensor_reading_monthly_aggregates_id"), ["id"], unique=False)
        batch_op.create_index(batch_op.f("ix_sensor_reading_monthly_aggregates_sensor_id"), ["sensor_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("sensor_reading_monthly_aggregates", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_sensor_reading_monthly_aggregates_sensor_id"))
        batch_op.drop_index(batch_op.f("ix_sensor_reading_monthly_aggregates_id"))
        batch_op.drop_index("ix_sensor_reading_aggregate_year_month")

    op.drop_table("sensor_reading_monthly_aggregates")
    # ### end Alembic commands ###
