"""initial_schema_14_tables

Revision ID: 9021458f6b9f
Revises:
Create Date: 2026-05-10 11:56:05.380841

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9021458f6b9f"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "crop_types",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("scientific_name", sa.String(length=150), nullable=True),
        sa.Column("optimal_ph_min", sa.Float(), nullable=True),
        sa.Column("optimal_ph_max", sa.Float(), nullable=True),
        sa.Column("optimal_temp_min", sa.Float(), nullable=True),
        sa.Column("optimal_temp_max", sa.Float(), nullable=True),
        sa.Column("water_need_mm_per_day", sa.Float(), nullable=True),
        sa.Column("growth_duration_days", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_crop_types")),
    )
    with op.batch_alter_table("crop_types", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_crop_types_id"), ["id"], unique=False)

    op.create_table(
        "model_performance_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("model_name", sa.String(length=100), nullable=False),
        sa.Column("prediction_data", sa.Text(), nullable=True),
        sa.Column("actual_data", sa.Text(), nullable=True),
        sa.Column("accuracy_score", sa.Float(), nullable=True),
        sa.Column("logged_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_model_performance_logs")),
    )
    with op.batch_alter_table("model_performance_logs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_model_performance_logs_id"), ["id"], unique=False)
        batch_op.create_index(batch_op.f("ix_model_performance_logs_logged_at"), ["logged_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_model_performance_logs_model_name"), ["model_name"], unique=False)

    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("email", sa.String(length=150), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=True),
        sa.Column("phone", sa.String(length=20), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_users_email"), ["email"], unique=True)
        batch_op.create_index(batch_op.f("ix_users_id"), ["id"], unique=False)

    op.create_table(
        "farms",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column("location_lat", sa.Float(), nullable=True),
        sa.Column("location_lng", sa.Float(), nullable=True),
        sa.Column("area_hectares", sa.Float(), nullable=True),
        sa.Column("city", sa.String(length=100), nullable=True),
        sa.Column("region", sa.String(length=100), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_farms_user_id_users")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_farms")),
    )
    with op.batch_alter_table("farms", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_farms_id"), ["id"], unique=False)

    op.create_table(
        "fields",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("farm_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column("area_hectares", sa.Float(), nullable=True),
        sa.Column("soil_type", sa.String(length=50), nullable=True),
        sa.Column("elevation_m", sa.Float(), nullable=True),
        sa.Column("crop_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["crop_id"], ["crop_types.id"], name=op.f("fk_fields_crop_id_crop_types")),
        sa.ForeignKeyConstraint(["farm_id"], ["farms.id"], name=op.f("fk_fields_farm_id_farms")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_fields")),
    )
    with op.batch_alter_table("fields", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_fields_id"), ["id"], unique=False)

    op.create_table(
        "weather_data",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("farm_id", sa.Integer(), nullable=True),
        sa.Column("recorded_at", sa.DateTime(), nullable=True),
        sa.Column("temperature_c", sa.Float(), nullable=True),
        sa.Column("humidity_percent", sa.Float(), nullable=True),
        sa.Column("precipitation_mm", sa.Float(), nullable=True),
        sa.Column("wind_speed_kmh", sa.Float(), nullable=True),
        sa.Column("solar_radiation", sa.Float(), nullable=True),
        sa.Column("uv_index", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(["farm_id"], ["farms.id"], name=op.f("fk_weather_data_farm_id_farms")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_weather_data")),
    )
    with op.batch_alter_table("weather_data", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_weather_data_id"), ["id"], unique=False)
        batch_op.create_index(batch_op.f("ix_weather_data_recorded_at"), ["recorded_at"], unique=False)
        batch_op.create_index("ix_weather_farm_recorded", ["farm_id", "recorded_at"], unique=False)

    op.create_table(
        "crop_plantings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("field_id", sa.Integer(), nullable=False),
        sa.Column("crop_id", sa.Integer(), nullable=False),
        sa.Column("planting_date", sa.DateTime(), nullable=False),
        sa.Column("expected_harvest_date", sa.DateTime(), nullable=True),
        sa.Column("actual_harvest_date", sa.DateTime(), nullable=True),
        sa.Column("season", sa.String(length=20), nullable=True),
        sa.Column("yield_kg_per_hectare", sa.Float(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=True),
        sa.ForeignKeyConstraint(["crop_id"], ["crop_types.id"], name=op.f("fk_crop_plantings_crop_id_crop_types")),
        sa.ForeignKeyConstraint(["field_id"], ["fields.id"], name=op.f("fk_crop_plantings_field_id_fields")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_crop_plantings")),
    )
    with op.batch_alter_table("crop_plantings", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_crop_plantings_crop_id"), ["crop_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_crop_plantings_field_id"), ["field_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_crop_plantings_id"), ["id"], unique=False)

    op.create_table(
        "fertilizer_recommendations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("field_id", sa.Integer(), nullable=False),
        sa.Column("crop_id", sa.Integer(), nullable=False),
        sa.Column("recommended_at", sa.DateTime(), nullable=True),
        sa.Column("nitrogen_kg", sa.Float(), nullable=True),
        sa.Column("phosphorus_kg", sa.Float(), nullable=True),
        sa.Column("potassium_kg", sa.Float(), nullable=True),
        sa.Column("total_fertilizer_kg", sa.Float(), nullable=True),
        sa.Column("recommendation_text", sa.Text(), nullable=True),
        sa.Column("is_applied", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["crop_id"], ["crop_types.id"], name=op.f("fk_fertilizer_recommendations_crop_id_crop_types")
        ),
        sa.ForeignKeyConstraint(
            ["field_id"], ["fields.id"], name=op.f("fk_fertilizer_recommendations_field_id_fields")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_fertilizer_recommendations")),
    )
    with op.batch_alter_table("fertilizer_recommendations", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_fertilizer_recommendations_field_id"), ["field_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_fertilizer_recommendations_id"), ["id"], unique=False)

    op.create_table(
        "irrigation_schedules",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("field_id", sa.Integer(), nullable=False),
        sa.Column("scheduled_date", sa.DateTime(), nullable=False),
        sa.Column("duration_min", sa.Integer(), nullable=True),
        sa.Column("water_amount_liters", sa.Float(), nullable=True),
        sa.Column("source", sa.String(length=20), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=True),
        sa.ForeignKeyConstraint(["field_id"], ["fields.id"], name=op.f("fk_irrigation_schedules_field_id_fields")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_irrigation_schedules")),
    )
    with op.batch_alter_table("irrigation_schedules", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_irrigation_schedules_field_id"), ["field_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_irrigation_schedules_id"), ["id"], unique=False)

    op.create_table(
        "plant_health_images",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("field_id", sa.Integer(), nullable=True),
        sa.Column("image_url", sa.String(length=500), nullable=True),
        sa.Column("captured_at", sa.DateTime(), nullable=True),
        sa.Column("diagnosis", sa.String(length=200), nullable=True),
        sa.Column("confidence_score", sa.Float(), nullable=True),
        sa.Column("severity", sa.String(length=20), nullable=True),
        sa.ForeignKeyConstraint(["field_id"], ["fields.id"], name=op.f("fk_plant_health_images_field_id_fields")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_plant_health_images")),
    )
    with op.batch_alter_table("plant_health_images", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_plant_health_images_id"), ["id"], unique=False)

    op.create_table(
        "sensors",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("field_id", sa.Integer(), nullable=False),
        sa.Column("sensor_type", sa.String(length=50), nullable=False),
        sa.Column("serial_number", sa.String(length=100), nullable=True),
        sa.Column("installation_date", sa.DateTime(), nullable=True),
        sa.Column("depth_cm", sa.Float(), nullable=True),
        sa.Column("lat", sa.Float(), nullable=True),
        sa.Column("lng", sa.Float(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=True),
        sa.ForeignKeyConstraint(["field_id"], ["fields.id"], name=op.f("fk_sensors_field_id_fields")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sensors")),
        sa.UniqueConstraint("serial_number", name=op.f("uq_sensors_serial_number")),
    )
    with op.batch_alter_table("sensors", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_sensors_field_id"), ["field_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_sensors_id"), ["id"], unique=False)

    op.create_table(
        "soil_analyses",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("field_id", sa.Integer(), nullable=False),
        sa.Column("analysis_date", sa.DateTime(), nullable=True),
        sa.Column("ph_level", sa.Float(), nullable=True),
        sa.Column("organic_matter_pct", sa.Float(), nullable=True),
        sa.Column("nitrogen_mg_kg", sa.Float(), nullable=True),
        sa.Column("phosphorus_mg_kg", sa.Float(), nullable=True),
        sa.Column("potassium_mg_kg", sa.Float(), nullable=True),
        sa.Column("calcium_mg_kg", sa.Float(), nullable=True),
        sa.Column("magnesium_mg_kg", sa.Float(), nullable=True),
        sa.Column("texture_class", sa.String(length=50), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["field_id"], ["fields.id"], name=op.f("fk_soil_analyses_field_id_fields")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_soil_analyses")),
    )
    with op.batch_alter_table("soil_analyses", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_soil_analyses_field_id"), ["field_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_soil_analyses_id"), ["id"], unique=False)

    op.create_table(
        "system_alerts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("farm_id", sa.Integer(), nullable=True),
        sa.Column("field_id", sa.Integer(), nullable=True),
        sa.Column("alert_type", sa.String(length=50), nullable=False),
        sa.Column("severity", sa.String(length=20), nullable=True),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("is_resolved", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["farm_id"], ["farms.id"], name=op.f("fk_system_alerts_farm_id_farms")),
        sa.ForeignKeyConstraint(["field_id"], ["fields.id"], name=op.f("fk_system_alerts_field_id_fields")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_system_alerts")),
    )
    with op.batch_alter_table("system_alerts", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_system_alerts_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_system_alerts_farm_id"), ["farm_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_system_alerts_field_id"), ["field_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_system_alerts_id"), ["id"], unique=False)

    op.create_table(
        "soil_moisture_readings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("sensor_id", sa.Integer(), nullable=False),
        sa.Column("reading_timestamp", sa.DateTime(), nullable=True),
        sa.Column("moisture_percent", sa.Float(), nullable=False),
        sa.Column("depth_cm", sa.Float(), nullable=True),
        sa.Column("soil_temperature_c", sa.Float(), nullable=True),
        sa.Column("electrical_conductivity", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["sensor_id"], ["sensors.id"], name=op.f("fk_soil_moisture_readings_sensor_id_sensors")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_soil_moisture_readings")),
    )
    with op.batch_alter_table("soil_moisture_readings", schema=None) as batch_op:
        batch_op.create_index("ix_readings_sensor_timestamp", ["sensor_id", "reading_timestamp"], unique=False)
        batch_op.create_index(batch_op.f("ix_soil_moisture_readings_id"), ["id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_soil_moisture_readings_reading_timestamp"), ["reading_timestamp"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("soil_moisture_readings", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_soil_moisture_readings_reading_timestamp"))
        batch_op.drop_index(batch_op.f("ix_soil_moisture_readings_id"))
        batch_op.drop_index("ix_readings_sensor_timestamp")

    op.drop_table("soil_moisture_readings")
    with op.batch_alter_table("system_alerts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_system_alerts_id"))
        batch_op.drop_index(batch_op.f("ix_system_alerts_field_id"))
        batch_op.drop_index(batch_op.f("ix_system_alerts_farm_id"))
        batch_op.drop_index(batch_op.f("ix_system_alerts_created_at"))

    op.drop_table("system_alerts")
    with op.batch_alter_table("soil_analyses", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_soil_analyses_id"))
        batch_op.drop_index(batch_op.f("ix_soil_analyses_field_id"))

    op.drop_table("soil_analyses")
    with op.batch_alter_table("sensors", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_sensors_id"))
        batch_op.drop_index(batch_op.f("ix_sensors_field_id"))

    op.drop_table("sensors")
    with op.batch_alter_table("plant_health_images", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_plant_health_images_id"))

    op.drop_table("plant_health_images")
    with op.batch_alter_table("irrigation_schedules", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_irrigation_schedules_id"))
        batch_op.drop_index(batch_op.f("ix_irrigation_schedules_field_id"))

    op.drop_table("irrigation_schedules")
    with op.batch_alter_table("fertilizer_recommendations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_fertilizer_recommendations_id"))
        batch_op.drop_index(batch_op.f("ix_fertilizer_recommendations_field_id"))

    op.drop_table("fertilizer_recommendations")
    with op.batch_alter_table("crop_plantings", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_crop_plantings_id"))
        batch_op.drop_index(batch_op.f("ix_crop_plantings_field_id"))
        batch_op.drop_index(batch_op.f("ix_crop_plantings_crop_id"))

    op.drop_table("crop_plantings")
    with op.batch_alter_table("weather_data", schema=None) as batch_op:
        batch_op.drop_index("ix_weather_farm_recorded")
        batch_op.drop_index(batch_op.f("ix_weather_data_recorded_at"))
        batch_op.drop_index(batch_op.f("ix_weather_data_id"))

    op.drop_table("weather_data")
    with op.batch_alter_table("fields", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_fields_id"))

    op.drop_table("fields")
    with op.batch_alter_table("farms", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_farms_id"))

    op.drop_table("farms")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_id"))
        batch_op.drop_index(batch_op.f("ix_users_email"))

    op.drop_table("users")
    with op.batch_alter_table("model_performance_logs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_model_performance_logs_model_name"))
        batch_op.drop_index(batch_op.f("ix_model_performance_logs_logged_at"))
        batch_op.drop_index(batch_op.f("ix_model_performance_logs_id"))

    op.drop_table("model_performance_logs")
    with op.batch_alter_table("crop_types", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_crop_types_id"))

    op.drop_table("crop_types")
    # ### end Alembic commands ###
